#!/usr/bin/env bash
cd $(dirname $0)

set -ex

# Make sure we have the latest source image
# for IMAGE in runtime builder; do
#     sudo docker pull kayess/fost-$IMAGE
# done

# Compile the code
rm -rf ../dist-docker
sudo docker run -v $(pwd)/..:/src -u $(id -u):$(id -g) \
    -it kayess/fost-builder fost-build docker/compile toolset=gcc release
strip ../dist-docker/bin/* ../dist-docker/lib/*

# Build base beanbag runtime
sudo docker build -t kayess/beanbag ../dist-docker
#sudo docker push kayess/beanbag

# Build and push the images
# for BUILD in gtf raw wiki; do
#     sudo docker build -t kayess/beanbag-$BUILD ../dist-docker
#     sudo docker push kayess/beanbag-$BUILD
# done
