#!/usr/bin/env bash
cd $(dirname $0)

set -ex

function dockerize {
    sed -i s/:latest/:$2/ ../dist-docker/${3}Dockerfile
    sudo docker build -t kayess/$1:$2 ../dist-docker/$3
    sudo docker push kayess/$1:$2
}

for RELEASE in precise trusty; do
    # Make sure we have the latest source image
    for IMAGE in runtime builder; do
        sudo docker pull kayess/fost-$IMAGE:$RELEASE
    done

    # Compile the code
    rm -rf ../dist-docker
    sudo docker run -v $(pwd)/..:/src -u $(id -u):$(id -g) \
        -it kayess/fost-builder:$RELEASE fost-build docker/compile toolset=gcc release
    strip ../dist-docker/bin/* ../dist-docker/lib/*

    # Build base beanbag runtime
    dockerize beanbag $RELEASE

    # Build and push the example images
    for BUILD in gtf; do
        dockerize $BUILD $RELEASE docker/$BUILD/
        sudo docker push kayess/beanbag-$BUILD:$RELEASE
    done
done

for IMAGE in beanbag beanbag-gtf; do
    sudo docker tag kayess/$IMAGE:$RELEASE kayess/$IMAGE:latest
done
